import { WorksWheelItem } from './types';

export const PORTFOLIO_PROJECTS: WorksWheelItem[] = [
  {
    id: 'fault-lab',
    title: 'Interactive Fault Lab',
    category: 'Network Simulation',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    href: '#interactive-lab',
    description: 'Eight interactive fault scenarios examining cable breaks, netmask misconfigurations, and gateway dropped frames.',
    badge: 'Simulation 01',
  },
  {
    id: 'layered-method',
    title: 'OSI Diagnostic Hierarchy',
    category: 'Engineering Theory',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80',
    href: '#theory',
    description: 'Systematic bottom-up diagnostic methodology from Layer 1 physical carrier verification through Layer 7 application services.',
    badge: 'Module 01',
  },
  {
    id: 'packet-simulator',
    title: 'Packet Flow Simulator',
    category: 'Interactive Lab',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    href: '#minigame',
    description: 'Real-time routing inspection lab simulating transit packet flow, hop degradation, and firewall state filtering.',
    badge: 'Laboratory Sim',
  },
  {
    id: 'diagnostic-toolbox',
    title: 'Diagnostic Utilities Suite',
    category: 'Protocol Utilities',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=1200&q=80',
    href: '#module-02',
    description: 'Technical dissection of ping (ICMP Echo), traceroute (TTL decrement), ipconfig, nslookup, arp, and netstat.',
    badge: 'Module 02',
  },
  {
    id: 'fault-matrix',
    title: 'Fault Signature Matrix',
    category: 'Diagnostic Reference',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    href: '#module-03',
    description: 'Definitive diagnostic fingerprint table matching raw terminal output to root cause failure modes and validated remediation steps.',
    badge: 'Module 03',
  },
  {
    id: 'socket-probes',
    title: 'Socket Reachability Probes',
    category: 'Systems Code',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    href: '#module-04',
    description: 'Production-grade socket probe implementations in C, C++, Python, and Java with non-blocking timeouts and latency tracking.',
    badge: 'Module 04',
  },
  {
    id: 'pre-test',
    title: 'Diagnostic Pre-Test',
    category: 'Assessment Phase I',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1200&q=80',
    href: '#pre-test',
    description: 'Ten foundational multiple-choice questions assessing comprehension of ARP, ICMP types, subnet boundaries, and APIPA.',
    badge: 'Pre-Test',
  },
  {
    id: 'post-test',
    title: 'Verification Post-Test',
    category: 'Assessment Phase II',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    href: '#post-test',
    description: 'Advanced assessment evaluating multi-hop traceroute diagnosis, asymmetric routing analysis, and firewall ACL troubleshooting.',
    badge: 'Post-Test',
  },
  {
    id: 'conclusion-standards',
    title: 'Academic Standards & RFCs',
    category: 'Syllabus & Research',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    href: '#conclusion',
    description: 'Synthesis of troubleshooting findings cross-referenced with IETF standards including RFC 792, RFC 826, and RFC 1122.',
    badge: 'Synthesis',
  },
];
